"""Generate a single Caddyfile that serves the supported built CUA-Gym-Hub mocks.

The mocks keep their canonical state in the browser (localStorage), and their
Vite dev/preview middleware is only a mirror of it. SurfGym gives each episode
its own BrowserContext, so the only thing the app host still has to provide is
the read-only initial state a task boots from. That makes static serving
sufficient:

    /              -> <app>/dist                    SPA, history fallback
    /state?sid=ID  -> <state_dir>/<APP_KEY>/ID.json read-only initial state
                       or ``default.json`` when no task seed exists
    /post          -> 204                           client mirrors state here
                                                    and ignores failures

State is namespaced per app, not per task alone: a cross-app task uses one sid
across 2-4 apps but POSTs a *different* state to each, so a flat directory
would serve one app's JSON on another app's port.

One Caddy process replaces the per-app Node preview servers.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from surfgym_task.cua.app_registry import key_from_app_dir
from surfgym_task.cua.webapp_manifest import DIRECT_WEB_APPS

# deploy-all.sh assigns consecutive ports ordered by directory name.
DEFAULT_START_PORT = 8000

_SITE_TEMPLATE = """\
:{port} {{
\troot * {dist}
\tencode gzip

\thandle /post* {{
\t\trespond 204
\t}}

\thandle /state* {{
\t\troot * {state_dir}/{app_key}
\t\trewrite * /{{http.request.uri.query.sid}}.json
\t\ttry_files {{path}} /default.json
\t\tfile_server
\t}}

\thandle {{
\t\ttry_files {{path}} /index.html
\t\tfile_server
\t}}
}}
"""


def discover_supported_apps(websites_dir: Path, *, built_only: bool) -> list[str]:
    """Return only the manifest-listed 28 apps, never incidental Hub builds."""
    supported = [app.app_dir for app in DIRECT_WEB_APPS]
    missing = [app for app in supported if not (websites_dir / app).is_dir()]
    if missing:
        raise FileNotFoundError(f"missing manifest app directories: {', '.join(missing)}")
    if built_only:
        return [app for app in supported if (websites_dir / app / "dist" / "index.html").is_file()]
    return supported


def assign_ports(selected: list[str], start_port: int) -> dict[str, int]:
    """Use pinned upstream offsets even though only 28 apps are vendored."""
    offset_by_dir = {app.app_dir: app.hub_port_offset for app in DIRECT_WEB_APPS}
    unknown = sorted(set(selected) - set(offset_by_dir))
    if unknown:
        raise ValueError(f"unsupported app directories: {', '.join(unknown)}")
    return {app: start_port + offset_by_dir[app] for app in selected}


def render(
    websites_dir: Path,
    state_dir: Path,
    ports: dict[str, int],
) -> str:
    blocks = [
        _SITE_TEMPLATE.format(
            port=port,
            dist=(websites_dir / app / "dist").as_posix(),
            state_dir=state_dir.as_posix(),
            app_key=key_from_app_dir(app),
        )
        for app, port in sorted(ports.items(), key=lambda item: item[1])
    ]
    # The admin endpoint stays on its localhost default so `caddy stop` works;
    # turning it off leaves no way to shut the server down cleanly.
    header = (
        "# Generated by scripts/cua_hub_deploy/gen_caddyfile.py -- do not edit by hand.\n"
        "{\n\tauto_https off\n}\n\n"
    )
    return header + "\n".join(blocks)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("websites_dir", type=Path, help="CUA-Gym-Hub/websites")
    parser.add_argument("--state-dir", type=Path, required=True, help="per-task initial state JSON")
    parser.add_argument("--out", type=Path, required=True, help="Caddyfile to write")
    parser.add_argument("--ports-out", type=Path, required=True, help="app key -> URL map")
    parser.add_argument("--start-port", type=int, default=DEFAULT_START_PORT)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument(
        "--require-all",
        action="store_true",
        help="fail unless all 28 manifest apps have dist/index.html",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    websites_dir: Path = args.websites_dir.resolve()

    selected = discover_supported_apps(websites_dir, built_only=True)
    if args.require_all and len(selected) != len(DIRECT_WEB_APPS):
        missing = sorted({app.app_dir for app in DIRECT_WEB_APPS} - set(selected))
        raise SystemExit(f"{len(missing)} supported app(s) missing dist/index.html: {', '.join(missing)}")
    if not selected:
        raise SystemExit(f"no built apps under {websites_dir} (run build_all.sh first)")

    ports = assign_ports(selected, args.start_port)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(websites_dir, args.state_dir.resolve(), ports), encoding="utf-8")

    url_map = {key_from_app_dir(app): f"http://{args.host}:{port}" for app, port in ports.items()}
    args.ports_out.parent.mkdir(parents=True, exist_ok=True)
    args.ports_out.write_text(json.dumps(url_map, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"{len(selected)} app(s) -> {args.out}")
    for app, port in sorted(ports.items(), key=lambda item: item[1]):
        print(f"  {port}  {app}")


if __name__ == "__main__":
    main()
