"""Offline compatibility CLI for the shared local static-site host contract.

Runtime orchestration calls ``surfgym_fixture.local_static_host`` directly.
This wrapper remains for importer/audit workflows that need a site-only
Caddyfile and the same stable ``ports.json`` mapping.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from surfgym_contracts.local_static_sites import LOCAL_STATIC_SITES, LocalStaticSite
from surfgym_fixture.local_static_host import render_ports, render_site_block

DEFAULT_START_PORT = 8000


def _dir_by_name() -> dict[str, LocalStaticSite]:
    return {Path(site.source_dir).name: site for site in LOCAL_STATIC_SITES}


def discover_supported_apps(websites_dir: Path, *, built_only: bool) -> list[str]:
    supported = [Path(site.source_dir).name for site in LOCAL_STATIC_SITES]
    missing = [app for app in supported if not (websites_dir / app).is_dir()]
    if missing:
        raise FileNotFoundError(f"missing runtime app directories: {', '.join(missing)}")
    if built_only:
        return [app for app in supported if (websites_dir / app / "dist" / "index.html").is_file()]
    return supported


def assign_ports(selected: list[str], start_port: int) -> dict[str, int]:
    if start_port != DEFAULT_START_PORT:
        raise ValueError(
            "local static-site ports are fixed; --start-port must remain 8000"
        )
    sites = _dir_by_name()
    unknown = sorted(set(selected) - set(sites))
    if unknown:
        raise ValueError(f"unsupported app directories: {', '.join(unknown)}")
    return {app: sites[app].port for app in selected}


def render(websites_dir: Path, state_dir: Path, ports: dict[str, int]) -> str:
    expected = assign_ports(list(ports), DEFAULT_START_PORT)
    if ports != expected:
        raise ValueError(f"ports do not match shared local static-site contract: {ports!r}")
    sites = _dir_by_name()
    blocks = "\n".join(
        render_site_block(
            sites[app],
            websites_dir / app / "dist",
            state_dir,
        )
        for app, _port in sorted(ports.items(), key=lambda item: item[1])
    )
    return (
        "# Generated by the shared local static-site contract -- do not edit.\n"
        "{\n\tauto_https off\n\tadmin off\n}\n\n"
        + blocks
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("websites_dir", type=Path)
    parser.add_argument("--state-dir", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--ports-out", type=Path, required=True)
    parser.add_argument("--start-port", type=int, default=DEFAULT_START_PORT)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--require-all", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    websites_dir = args.websites_dir.resolve()
    selected = discover_supported_apps(websites_dir, built_only=True)
    if args.require_all and len(selected) != len(LOCAL_STATIC_SITES):
        supported = {Path(site.source_dir).name for site in LOCAL_STATIC_SITES}
        missing = sorted(supported - set(selected))
        raise SystemExit(
            f"{len(missing)} supported app(s) missing dist/index.html: {', '.join(missing)}"
        )
    if not selected:
        raise SystemExit(f"no built apps under {websites_dir}")
    ports = assign_ports(selected, args.start_port)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(websites_dir, args.state_dir.resolve(), ports), encoding="utf-8")
    selected_keys = {
        site.key for site in LOCAL_STATIC_SITES if Path(site.source_dir).name in selected
    }
    url_map = {
        key: url.replace("127.0.0.1", args.host)
        for key, url in render_ports().items()
        if key in selected_keys
    }
    args.ports_out.parent.mkdir(parents=True, exist_ok=True)
    args.ports_out.write_text(
        json.dumps(url_map, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
