"""Render the one Caddy process that owns SurfGym's local static content."""

from __future__ import annotations

import argparse
import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence

from surfgym_contracts.local_static_sites import LOCAL_STATIC_SITES, LocalStaticSite

FIXTURE_PORT = 3000


@dataclass(frozen=True)
class RenderInputs:
    repo_root: Path
    fixture_dist: Path
    state_dir: Path


def _caddy_path(path: Path) -> str:
    return json.dumps(path.resolve().as_posix())


def render_site_block(site: LocalStaticSite, dist: Path, state_dir: Path) -> str:
    state_root = state_dir / site.key
    return f"""\
http://127.0.0.1:{site.port} {{
\troot * {_caddy_path(dist)}
\tencode gzip
\theader Cache-Control \"no-store\"

\thandle /post {{
\t\trespond 204
\t}}

\t@valid_state {{
\t\tpath /state
\t\texpression `{{query.sid}}.matches('^[A-Za-z0-9][A-Za-z0-9._-]{{0,127}}$')`
\t}}
\thandle @valid_state {{
\t\troot * {_caddy_path(state_root)}
\t\trewrite * /{{http.request.uri.query.sid}}.json
\t\ttry_files {{path}} /default.json
\t\tfile_server
\t}}

\thandle /state {{
\t\trespond 400
\t}}

\thandle {{
\t\ttry_files {{path}} /index.html
\t\tfile_server
\t}}
}}
"""


def render_caddyfile(inputs: RenderInputs) -> str:
    fixture = f"""\
http://127.0.0.1:{FIXTURE_PORT} {{
\troot * {_caddy_path(inputs.fixture_dist)}
\tencode zstd gzip
\theader Cache-Control \"no-store\"
\ttry_files {{path}} {{path}}/index.html =404
\tfile_server {{
\t\tprecompressed zstd gzip
\t}}
}}
"""
    sites = "\n".join(
        render_site_block(
            site,
            inputs.repo_root / site.source_dir / "dist",
            inputs.state_dir,
        )
        for site in LOCAL_STATIC_SITES
    )
    return (
        "# Generated by surfgym_fixture.local_static_host -- do not edit.\n"
        "{\n\tauto_https off\n\tadmin off\n}\n\n"
        f"{fixture}\n{sites}"
    )


def render_ports() -> dict[str, str]:
    return {
        site.key: f"http://127.0.0.1:{site.port}"
        for site in sorted(LOCAL_STATIC_SITES, key=lambda item: item.key)
    }


def validate_builds(inputs: RenderInputs) -> None:
    missing: list[str] = []
    fixture_index = inputs.fixture_dist / "index.html"
    if not fixture_index.is_file():
        missing.append(f"fixture ({fixture_index})")
    for site in LOCAL_STATIC_SITES:
        index = inputs.repo_root / site.source_dir / "dist" / "index.html"
        if not index.is_file():
            missing.append(f"{site.key} ({index})")
    if missing:
        raise FileNotFoundError("missing static build(s): " + ", ".join(missing))


def _stage(path: Path, content: bytes) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise
    return temporary


def write_runtime_files(inputs: RenderInputs, output_dir: Path) -> None:
    validate_builds(inputs)
    contents: Mapping[Path, bytes] = {
        output_dir / "Caddyfile": render_caddyfile(inputs).encode("utf-8"),
        output_dir / "ports.json": (
            json.dumps(render_ports(), indent=2, sort_keys=True) + "\n"
        ).encode("utf-8"),
    }
    originals = {
        destination: destination.read_bytes() if destination.is_file() else None
        for destination in contents
    }
    staged: list[tuple[Path, Path]] = []
    replaced: list[Path] = []
    try:
        for destination, content in contents.items():
            staged.append((_stage(destination, content), destination))
        for temporary, destination in staged:
            os.replace(temporary, destination)
            replaced.append(destination)
    except BaseException:
        rollback_error: OSError | None = None
        for destination in reversed(replaced):
            try:
                original = originals[destination]
                if original is None:
                    destination.unlink(missing_ok=True)
                else:
                    restoration = _stage(destination, original)
                    try:
                        os.replace(restoration, destination)
                    finally:
                        restoration.unlink(missing_ok=True)
            except OSError as exc:
                rollback_error = exc
        if rollback_error is not None:
            raise RuntimeError("failed to restore the previous static-host generation") from rollback_error
        raise
    finally:
        for temporary, _ in staged:
            temporary.unlink(missing_ok=True)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--fixture-dist", type=Path, required=True)
    parser.add_argument("--state-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    inputs = RenderInputs(
        repo_root=args.repo_root.resolve(),
        fixture_dist=args.fixture_dist.resolve(),
        state_dir=args.state_dir.resolve(),
    )
    try:
        validate_builds(inputs)
        render_caddyfile(inputs)
        render_ports()
        if not args.check:
            write_runtime_files(inputs, args.output_dir.resolve())
    except OSError as exc:
        print(f"Static host error: {exc}")
        return 2
    mode = "validated" if args.check else "generated"
    print(f"Local static host {mode}: {len(LOCAL_STATIC_SITES)} distinct sites.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
